export const style = {
    flexCenter: 'flex justify-center items-center',
    flexStart: 'flex justify-center items-start',
    flexEvenly: 'justify-evenly flex items-center',
    flexBtw: 'justify-between flex items-center',
    heading1: "flex justify-between items-center mt-4 relative",
    heading2: 'font-semibold text-sm',
    subHeading: 'text-[0.75rem] mt-1 text-slate-500',
    label: 'w-[45%] mr-4',
    input: 'border-2 border-black/10 mt-5 focus:border-btnColor px-2 py-3 pl-12 outline-none focus:border-2 focus:bg-blue-50 rounded-md backdrop-blur-lg',
    mastercard: 'w-8 absolute top-[70%] left-2',
    verified: 'w-8 absolute top-[70%] right-2 text-btnColor',
    inputError: 'text-red-600 text-[0.7rem] absolute -bottom-6 right-2',
    gridIcon: 'w-8 absolute top-[60%] right-2 text-slate-500 cursor-pointer',
    slash: 'translate-y-3 w-[10%] font-bold flex justify-center mx-1',
    submitBtn: 'text-[0.75rem] w-full text-center bg-btnColor text-white rounded-lg py-5 mt-6 hover:shadow-btnShadow transition-all',
    checkoutContainer: 'md:mt-0 mt-[4rem] md:pt-[10%] pt-[15%] sm:min-h-[90vh] md:min-h-[70vh] min-h-[70vh] relative flex-col',
    checkout: 'w-full rounded-xl absolute top-[19%]',
    apple: 'w-5 h-5 rounded-full bg-timerColor mr-2',
    detailsContainer: "flex justify-between my-4",
    detailText: 'text-slate-500 text-sm',
    subDetail: 'font-semibold flex justify-evenly items-center text-sm',
    closeBar: 'absolute top-2 right-4 cursor-pointer',
    payment: 'flex justify-evenly flex-col',
    pay: 'text-slate-500 text-[0.75rem] mb-2',
    money1: 'text-[0.75rem] font-light mr-3',
    money2: 'font-light text-[0.78rem]',
}